use_frameworks!

def shmtableview_dev
    pod 'SHMTableView', :path => '../'
end

target 'SHMTableView_Example' do
    shmtableview_dev
end

target 'SHMTableView_Tests' do
    shmtableview_dev
    pod 'Nimble'
end

target 'SHMTableView_Example_tvOS' do
    shmtableview_dev
end

target 'SHMTableView_Example_tvOS_Tests' do
    shmtableview_dev
    pod 'Nimble'
end

