use_frameworks!

target 'SHMTableView_Example' do
    pod 'SHMTableView', :path => '../'
  
    target 'SHMTableView_Tests' do
        inherit! :search_paths
        pod 'Nimble', '6.0.1'
    end
end

target 'SHMTableView_Example_tvOS' do
    pod 'SHMTableView', :path => '../'
    
    target 'SHMTableView_Example_tvOS_Tests' do
        inherit! :search_paths
        pod 'Nimble', '6.0.1'
    end
end
